### ISSUE TITLE
[question] todo-mvp Why the app don't show saved todo after I have killed the app

### ISSUE THREAD

**Issue by umitems** [googlesamples/android-architecture#202] opened 2016-09-26 06:38 UTC
1. When I add todos and then kill the app. Then I reopen the app I found no todo in it.
I though I already saved in sqlite. Is there anything wrong?

2. Did the app can save/load todo from network?

**Comment by JoseAlcerreca** [comment] 2016-09-26 08:55
Duplicate of #123

**Closed by JoseAlcerreca** 2016-09-26 08:55 UTC
