### ISSUE TITLE
Shrinker error: extraneous input '[]' expecting ')'

### ISSUE THREAD

**Issue by Jack-Xiao** [googlesamples/android-architecture#73] opened 2016-05-12 13:55 UTC
I download the android-architecture-todo program, and them i run it. but i got wrong, the follow is the message. I don't know how to do ?
<img width="1221" alt="2016-05-12 21 49 17" src="https://cloud.githubusercontent.com/assets/9278026/15217027/3ff6fb8c-188c-11e6-9930-039cf9b61c5d.png">

**Comment by foolchen** [comment] 2016-05-13 06:47
I encountered the same problem.

**Comment by foolchen** [comment] 2016-05-13 06:58
When I change `minifyEnabled` to `false`, the problem is solved .

**Comment by JoseAlcerreca** [comment] 2016-05-13 09:15
The problem is only hidden if you do that, and your method count will be bigger.

`proguard-android.txt` is the SDK's proguard file. I have not seen that error, let me investigate.

**Comment by JoseAlcerreca** [comment] 2016-05-13 09:19
What sample were you trying to build? I just updated todo-mvp to use the gradle plugin 2.1.0, from 2.1.0-beta3, can you try again?

**Comment by Jack-Xiao** [comment] 2016-05-13 10:18
@foolchen  thanks, It's work! however, what's happen.
@JoseAlcerreca my build project  is architecture-todo base model, and i relsove this problem follow foolchen method.

**Comment by JoseAlcerreca** [comment] 2016-05-13 10:54
Again, this doesn't solve the problem.

When you say base model do you mean todo-mvp?

Can you try with 2.1.0?

**Comment by Jack-Xiao** [comment] 2016-05-13 14:33
Yes, the todo-mvp,and link: https://github.com/googlesamples/android-architecture/tree/todo-mvp/
my project gradle version is also 2.1.0, and i share the problem todo-mvp project in my github :https://github.com/Jack-Xiao/todoapp

**Comment by Xiadalei** [comment] 2016-05-14 01:49
Same problem here.
Gradle 2.1.0 and with Android Studio 2.1.1 in Windows
Try to build every official model and fail with same error

**Comment by JoseAlcerreca** [comment] 2016-05-14 20:40
@Jack-Xiao are you on Windows too?

**Comment by Jack-Xiao** [comment] 2016-05-14 20:42
@JoseAlcerreca  my os is mac

**Comment by JoseAlcerreca** [comment] 2016-05-14 20:44
I've reported the problem to the build tools team.

**Comment by Jack-Xiao** [comment] 2016-05-14 20:46
thanks

**Comment by Jack-Xiao** [comment] 2016-05-14 21:11
sorry, i incaution closed this issue, anyone knows open it again?

**Comment by benol** [comment] 2016-05-16 12:27
Hi, this is Michal from the build tools team. I can't reproduce the problem, I tried git commit 10fbc69c71baa1ed8f963a68dd9f8c6fb990b12d in android-architecture, todo-mvp branch - and it built just fine. Are you using the same branch/project/commit? If not, can you post the commit number where you see the problem?

**Comment by malmstein** [comment] 2016-05-16 12:35
These two lines in the default `proguard-android.txt` file are the issue:

`void set*(%[]);`
`%[] get*();;`

As a quick fix this is how I made it work in the Content Providers sample:

https://github.com/googlesamples/android-architecture/blob/dev-todo-mvp-contentproviders/todoapp/app/proguard-android.txt

Basically, grabbing the default proguard-android file and adding it to the folder:
https://github.com/googlesamples/android-architecture/blob/dev-todo-mvp-contentproviders/todoapp/app/build.gradle#L22

**Comment by Jack-Xiao** [comment] 2016-05-17 02:09
@benol  i also use gradle version 2.1.0.
@malmstein it work with your file. It seems remove the problem get set method, and change Listener method?  And, what happend. All of us maybe want to know.

**Comment by benol** [comment] 2016-05-17 12:57
I can reproduce now, thanks. It's a known issue with the parser in 2.1, it's been fixed for 2.2.

**Comment by JoseAlcerreca** [comment] 2016-05-17 13:58
Please replace 

`            minifyEnabled true`

with

`            minifyEnabled false`

for the debug buildType, until 2.2 is out.

**Comment by JoseAlcerreca** [comment] 2016-06-03 17:03
This has been fixed in the tools, we'll update all samples next week.

**Closed** 2016-06-30 06:30 UTC
Labels: bug
